apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphdb-test-client.fullname" . }}
  labels:
    app: {{ include "graphdb-test-client.name" . }}
    chart: {{ include "graphdb-test-client.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "graphdb-test-client.name" . }}
    release: {{ .Release.Name }}
